/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StaticRouteRouteImport } from './routes/_static/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiLyricVideosRouteImport } from './routes/api/lyric-videos'
import { Route as StaticDocsIndexRouteImport } from './routes/_static/docs/index'
import { Route as AuthAppIndexRouteImport } from './routes/_auth/app/index'
import { Route as ApiLyricVideosIdRouteImport } from './routes/api/lyric-videos.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as StaticDocsNameRouteImport } from './routes/_static/docs/$name'
import { Route as AuthAppLyricVideosRouteImport } from './routes/_auth/app/lyric-videos'
import { Route as ApiLyricVideosIdRenderRouteImport } from './routes/api/lyric-videos.$id.render'
import { Route as ApiLyricVideosIdOutputRouteImport } from './routes/api/lyric-videos.$id.output'
import { Route as ApiLyricVideosIdAudioRouteImport } from './routes/api/lyric-videos.$id.audio'
import { Route as AuthAppPolarSubscriptionsRouteImport } from './routes/_auth/app/polar/subscriptions'
import { Route as AuthAppPolarPortalRouteImport } from './routes/_auth/app/polar/portal'
import { Route as AuthAppLyricVideosIdRouteImport } from './routes/_auth/app/lyric-videos.$id'
import { Route as AuthAppPolarCheckoutSuccessRouteImport } from './routes/_auth/app/polar/checkout.success'

const StaticRouteRoute = StaticRouteRouteImport.update({
  id: '/_static',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLyricVideosRoute = ApiLyricVideosRouteImport.update({
  id: '/api/lyric-videos',
  path: '/api/lyric-videos',
  getParentRoute: () => rootRouteImport,
} as any)
const StaticDocsIndexRoute = StaticDocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => StaticRouteRoute,
} as any)
const AuthAppIndexRoute = AuthAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiLyricVideosIdRoute = ApiLyricVideosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiLyricVideosRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const StaticDocsNameRoute = StaticDocsNameRouteImport.update({
  id: '/docs/$name',
  path: '/docs/$name',
  getParentRoute: () => StaticRouteRoute,
} as any)
const AuthAppLyricVideosRoute = AuthAppLyricVideosRouteImport.update({
  id: '/app/lyric-videos',
  path: '/app/lyric-videos',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiLyricVideosIdRenderRoute = ApiLyricVideosIdRenderRouteImport.update({
  id: '/render',
  path: '/render',
  getParentRoute: () => ApiLyricVideosIdRoute,
} as any)
const ApiLyricVideosIdOutputRoute = ApiLyricVideosIdOutputRouteImport.update({
  id: '/output',
  path: '/output',
  getParentRoute: () => ApiLyricVideosIdRoute,
} as any)
const ApiLyricVideosIdAudioRoute = ApiLyricVideosIdAudioRouteImport.update({
  id: '/audio',
  path: '/audio',
  getParentRoute: () => ApiLyricVideosIdRoute,
} as any)
const AuthAppPolarSubscriptionsRoute =
  AuthAppPolarSubscriptionsRouteImport.update({
    id: '/app/polar/subscriptions',
    path: '/app/polar/subscriptions',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthAppPolarPortalRoute = AuthAppPolarPortalRouteImport.update({
  id: '/app/polar/portal',
  path: '/app/polar/portal',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAppLyricVideosIdRoute = AuthAppLyricVideosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthAppLyricVideosRoute,
} as any)
const AuthAppPolarCheckoutSuccessRoute =
  AuthAppPolarCheckoutSuccessRouteImport.update({
    id: '/app/polar/checkout/success',
    path: '/app/polar/checkout/success',
    getParentRoute: () => AuthRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/lyric-videos': typeof ApiLyricVideosRouteWithChildren
  '/app/lyric-videos': typeof AuthAppLyricVideosRouteWithChildren
  '/docs/$name': typeof StaticDocsNameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/lyric-videos/$id': typeof ApiLyricVideosIdRouteWithChildren
  '/app': typeof AuthAppIndexRoute
  '/docs': typeof StaticDocsIndexRoute
  '/app/lyric-videos/$id': typeof AuthAppLyricVideosIdRoute
  '/app/polar/portal': typeof AuthAppPolarPortalRoute
  '/app/polar/subscriptions': typeof AuthAppPolarSubscriptionsRoute
  '/api/lyric-videos/$id/audio': typeof ApiLyricVideosIdAudioRoute
  '/api/lyric-videos/$id/output': typeof ApiLyricVideosIdOutputRoute
  '/api/lyric-videos/$id/render': typeof ApiLyricVideosIdRenderRoute
  '/app/polar/checkout/success': typeof AuthAppPolarCheckoutSuccessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/lyric-videos': typeof ApiLyricVideosRouteWithChildren
  '/app/lyric-videos': typeof AuthAppLyricVideosRouteWithChildren
  '/docs/$name': typeof StaticDocsNameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/lyric-videos/$id': typeof ApiLyricVideosIdRouteWithChildren
  '/app': typeof AuthAppIndexRoute
  '/docs': typeof StaticDocsIndexRoute
  '/app/lyric-videos/$id': typeof AuthAppLyricVideosIdRoute
  '/app/polar/portal': typeof AuthAppPolarPortalRoute
  '/app/polar/subscriptions': typeof AuthAppPolarSubscriptionsRoute
  '/api/lyric-videos/$id/audio': typeof ApiLyricVideosIdAudioRoute
  '/api/lyric-videos/$id/output': typeof ApiLyricVideosIdOutputRoute
  '/api/lyric-videos/$id/render': typeof ApiLyricVideosIdRenderRoute
  '/app/polar/checkout/success': typeof AuthAppPolarCheckoutSuccessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_static': typeof StaticRouteRouteWithChildren
  '/api/lyric-videos': typeof ApiLyricVideosRouteWithChildren
  '/_auth/app/lyric-videos': typeof AuthAppLyricVideosRouteWithChildren
  '/_static/docs/$name': typeof StaticDocsNameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/lyric-videos/$id': typeof ApiLyricVideosIdRouteWithChildren
  '/_auth/app/': typeof AuthAppIndexRoute
  '/_static/docs/': typeof StaticDocsIndexRoute
  '/_auth/app/lyric-videos/$id': typeof AuthAppLyricVideosIdRoute
  '/_auth/app/polar/portal': typeof AuthAppPolarPortalRoute
  '/_auth/app/polar/subscriptions': typeof AuthAppPolarSubscriptionsRoute
  '/api/lyric-videos/$id/audio': typeof ApiLyricVideosIdAudioRoute
  '/api/lyric-videos/$id/output': typeof ApiLyricVideosIdOutputRoute
  '/api/lyric-videos/$id/render': typeof ApiLyricVideosIdRenderRoute
  '/_auth/app/polar/checkout/success': typeof AuthAppPolarCheckoutSuccessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/lyric-videos'
    | '/app/lyric-videos'
    | '/docs/$name'
    | '/api/auth/$'
    | '/api/lyric-videos/$id'
    | '/app'
    | '/docs'
    | '/app/lyric-videos/$id'
    | '/app/polar/portal'
    | '/app/polar/subscriptions'
    | '/api/lyric-videos/$id/audio'
    | '/api/lyric-videos/$id/output'
    | '/api/lyric-videos/$id/render'
    | '/app/polar/checkout/success'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/lyric-videos'
    | '/app/lyric-videos'
    | '/docs/$name'
    | '/api/auth/$'
    | '/api/lyric-videos/$id'
    | '/app'
    | '/docs'
    | '/app/lyric-videos/$id'
    | '/app/polar/portal'
    | '/app/polar/subscriptions'
    | '/api/lyric-videos/$id/audio'
    | '/api/lyric-videos/$id/output'
    | '/api/lyric-videos/$id/render'
    | '/app/polar/checkout/success'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_static'
    | '/api/lyric-videos'
    | '/_auth/app/lyric-videos'
    | '/_static/docs/$name'
    | '/api/auth/$'
    | '/api/lyric-videos/$id'
    | '/_auth/app/'
    | '/_static/docs/'
    | '/_auth/app/lyric-videos/$id'
    | '/_auth/app/polar/portal'
    | '/_auth/app/polar/subscriptions'
    | '/api/lyric-videos/$id/audio'
    | '/api/lyric-videos/$id/output'
    | '/api/lyric-videos/$id/render'
    | '/_auth/app/polar/checkout/success'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  StaticRouteRoute: typeof StaticRouteRouteWithChildren
  ApiLyricVideosRoute: typeof ApiLyricVideosRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_static': {
      id: '/_static'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof StaticRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lyric-videos': {
      id: '/api/lyric-videos'
      path: '/api/lyric-videos'
      fullPath: '/api/lyric-videos'
      preLoaderRoute: typeof ApiLyricVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_static/docs/': {
      id: '/_static/docs/'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof StaticDocsIndexRouteImport
      parentRoute: typeof StaticRouteRoute
    }
    '/_auth/app/': {
      id: '/_auth/app/'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthAppIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/lyric-videos/$id': {
      id: '/api/lyric-videos/$id'
      path: '/$id'
      fullPath: '/api/lyric-videos/$id'
      preLoaderRoute: typeof ApiLyricVideosIdRouteImport
      parentRoute: typeof ApiLyricVideosRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_static/docs/$name': {
      id: '/_static/docs/$name'
      path: '/docs/$name'
      fullPath: '/docs/$name'
      preLoaderRoute: typeof StaticDocsNameRouteImport
      parentRoute: typeof StaticRouteRoute
    }
    '/_auth/app/lyric-videos': {
      id: '/_auth/app/lyric-videos'
      path: '/app/lyric-videos'
      fullPath: '/app/lyric-videos'
      preLoaderRoute: typeof AuthAppLyricVideosRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/lyric-videos/$id/render': {
      id: '/api/lyric-videos/$id/render'
      path: '/render'
      fullPath: '/api/lyric-videos/$id/render'
      preLoaderRoute: typeof ApiLyricVideosIdRenderRouteImport
      parentRoute: typeof ApiLyricVideosIdRoute
    }
    '/api/lyric-videos/$id/output': {
      id: '/api/lyric-videos/$id/output'
      path: '/output'
      fullPath: '/api/lyric-videos/$id/output'
      preLoaderRoute: typeof ApiLyricVideosIdOutputRouteImport
      parentRoute: typeof ApiLyricVideosIdRoute
    }
    '/api/lyric-videos/$id/audio': {
      id: '/api/lyric-videos/$id/audio'
      path: '/audio'
      fullPath: '/api/lyric-videos/$id/audio'
      preLoaderRoute: typeof ApiLyricVideosIdAudioRouteImport
      parentRoute: typeof ApiLyricVideosIdRoute
    }
    '/_auth/app/polar/subscriptions': {
      id: '/_auth/app/polar/subscriptions'
      path: '/app/polar/subscriptions'
      fullPath: '/app/polar/subscriptions'
      preLoaderRoute: typeof AuthAppPolarSubscriptionsRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/app/polar/portal': {
      id: '/_auth/app/polar/portal'
      path: '/app/polar/portal'
      fullPath: '/app/polar/portal'
      preLoaderRoute: typeof AuthAppPolarPortalRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/app/lyric-videos/$id': {
      id: '/_auth/app/lyric-videos/$id'
      path: '/$id'
      fullPath: '/app/lyric-videos/$id'
      preLoaderRoute: typeof AuthAppLyricVideosIdRouteImport
      parentRoute: typeof AuthAppLyricVideosRoute
    }
    '/_auth/app/polar/checkout/success': {
      id: '/_auth/app/polar/checkout/success'
      path: '/app/polar/checkout/success'
      fullPath: '/app/polar/checkout/success'
      preLoaderRoute: typeof AuthAppPolarCheckoutSuccessRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthAppLyricVideosRouteChildren {
  AuthAppLyricVideosIdRoute: typeof AuthAppLyricVideosIdRoute
}

const AuthAppLyricVideosRouteChildren: AuthAppLyricVideosRouteChildren = {
  AuthAppLyricVideosIdRoute: AuthAppLyricVideosIdRoute,
}

const AuthAppLyricVideosRouteWithChildren =
  AuthAppLyricVideosRoute._addFileChildren(AuthAppLyricVideosRouteChildren)

interface AuthRouteRouteChildren {
  AuthAppLyricVideosRoute: typeof AuthAppLyricVideosRouteWithChildren
  AuthAppIndexRoute: typeof AuthAppIndexRoute
  AuthAppPolarPortalRoute: typeof AuthAppPolarPortalRoute
  AuthAppPolarSubscriptionsRoute: typeof AuthAppPolarSubscriptionsRoute
  AuthAppPolarCheckoutSuccessRoute: typeof AuthAppPolarCheckoutSuccessRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAppLyricVideosRoute: AuthAppLyricVideosRouteWithChildren,
  AuthAppIndexRoute: AuthAppIndexRoute,
  AuthAppPolarPortalRoute: AuthAppPolarPortalRoute,
  AuthAppPolarSubscriptionsRoute: AuthAppPolarSubscriptionsRoute,
  AuthAppPolarCheckoutSuccessRoute: AuthAppPolarCheckoutSuccessRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface StaticRouteRouteChildren {
  StaticDocsNameRoute: typeof StaticDocsNameRoute
  StaticDocsIndexRoute: typeof StaticDocsIndexRoute
}

const StaticRouteRouteChildren: StaticRouteRouteChildren = {
  StaticDocsNameRoute: StaticDocsNameRoute,
  StaticDocsIndexRoute: StaticDocsIndexRoute,
}

const StaticRouteRouteWithChildren = StaticRouteRoute._addFileChildren(
  StaticRouteRouteChildren,
)

interface ApiLyricVideosIdRouteChildren {
  ApiLyricVideosIdAudioRoute: typeof ApiLyricVideosIdAudioRoute
  ApiLyricVideosIdOutputRoute: typeof ApiLyricVideosIdOutputRoute
  ApiLyricVideosIdRenderRoute: typeof ApiLyricVideosIdRenderRoute
}

const ApiLyricVideosIdRouteChildren: ApiLyricVideosIdRouteChildren = {
  ApiLyricVideosIdAudioRoute: ApiLyricVideosIdAudioRoute,
  ApiLyricVideosIdOutputRoute: ApiLyricVideosIdOutputRoute,
  ApiLyricVideosIdRenderRoute: ApiLyricVideosIdRenderRoute,
}

const ApiLyricVideosIdRouteWithChildren =
  ApiLyricVideosIdRoute._addFileChildren(ApiLyricVideosIdRouteChildren)

interface ApiLyricVideosRouteChildren {
  ApiLyricVideosIdRoute: typeof ApiLyricVideosIdRouteWithChildren
}

const ApiLyricVideosRouteChildren: ApiLyricVideosRouteChildren = {
  ApiLyricVideosIdRoute: ApiLyricVideosIdRouteWithChildren,
}

const ApiLyricVideosRouteWithChildren = ApiLyricVideosRoute._addFileChildren(
  ApiLyricVideosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  StaticRouteRoute: StaticRouteRouteWithChildren,
  ApiLyricVideosRoute: ApiLyricVideosRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
